"""initial schema

Revision ID: 169bfb0d3e8d
Revises: 
Create Date: 2026-09-17 14:06:21.742864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169bfb0d3e8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.Enum('MOCK', 'API', 'SCRAPER', 'MARKETPLACE', 'MANUAL', name='sourcetype'), nullable=False),
    sa.Column('base_url', sa.String(length=1024), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('marketplace_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'CLOSED', name='listingstatus'), nullable=False),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_products_marketplace_id'), 'marketplace_products', ['marketplace_id'], unique=False)
    op.create_index(op.f('ix_marketplace_products_product_id'), 'marketplace_products', ['product_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('marketplace_id', sa.String(length=36), nullable=False),
    sa.Column('buy_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sell_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('marketplace_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('other_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('roi', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('margin', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('competition_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('demand_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ai_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.Enum('REJECTED', 'REVIEW', 'PROMISING', 'APPROVED', name='opportunitystatus'), nullable=False),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_marketplace_id'), 'opportunities', ['marketplace_id'], unique=False)
    op.create_index(op.f('ix_opportunities_product_id'), 'opportunities', ['product_id'], unique=False)
    op.create_index(op.f('ix_opportunities_source_id'), 'opportunities', ['source_id'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_captured_at'), 'price_history', ['captured_at'], unique=False)
    op.create_index(op.f('ix_price_history_product_id'), 'price_history', ['product_id'], unique=False)
    op.create_index(op.f('ix_price_history_source_id'), 'price_history', ['source_id'], unique=False)
    op.create_table('source_products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('stock_available', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_products_product_id'), 'source_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_source_products_source_id'), 'source_products', ['source_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('marketplace_order_id', sa.String(length=255), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('supplier_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('marketplace_fees', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('other_costs', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expected_profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'AWAITING_SUPPLIER_PURCHASE', 'PURCHASED_FROM_SUPPLIER', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('customer_shipping_status', sa.Enum('NOT_SHIPPED', 'SHIPPED', 'IN_TRANSIT', 'DELIVERED', 'RETURNED', name='customershippingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_marketplace_order_id'), 'orders', ['marketplace_order_id'], unique=False)
    op.create_index(op.f('ix_orders_product_id'), 'orders', ['product_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_product_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_marketplace_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_source_products_source_id'), table_name='source_products')
    op.drop_index(op.f('ix_source_products_product_id'), table_name='source_products')
    op.drop_table('source_products')
    op.drop_index(op.f('ix_price_history_source_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_product_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_captured_at'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_source_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_product_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_marketplace_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_marketplace_products_product_id'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_marketplace_id'), table_name='marketplace_products')
    op.drop_table('marketplace_products')
    op.drop_table('sources')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_table('marketplaces')
    # ### end Alembic commands ###
