"""Add autopilot phase 0 tables: lifecycle, market gap, listing drafts, analytics

Revision ID: 79343d91d477
Revises: 169bfb0d3e8d
Create Date: 2026-09-26 19:40:27.581790

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79343d91d477"
down_revision: Union[str, None] = "169bfb0d3e8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("opportunity_id", sa.String(length=36), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum("DETECTED", "PUBLISHED", "SOLD", "EXPIRED", name="analyticseventtype"),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=36), nullable=True),
        sa.Column("estimated_margin", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("real_margin", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("time_to_sale_minutes", sa.Integer(), nullable=True),
        sa.Column("confidence_score_at_detection", sa.Integer(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analytics_events_event_type"), "analytics_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_analytics_events_opportunity_id"),
        "analytics_events",
        ["opportunity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_recorded_at"), "analytics_events", ["recorded_at"], unique=False
    )
    op.create_table(
        "listing_drafts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("opportunity_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=60), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("bullets", sa.Text(), nullable=True),
        sa.Column("attributes", sa.Text(), nullable=True),
        sa.Column("image_urls", sa.Text(), nullable=True),
        sa.Column("category_id", sa.String(length=32), nullable=True),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "READY", "PUBLISHED", "REJECTED", name="listingdraftstatus"),
            nullable=False,
        ),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_listing_drafts_opportunity_id"), "listing_drafts", ["opportunity_id"], unique=False
    )
    op.create_index(op.f("ix_listing_drafts_status"), "listing_drafts", ["status"], unique=False)
    op.create_table(
        "market_gap_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("catalog_product_id", sa.String(length=64), nullable=False),
        sa.Column("opportunity_id", sa.String(length=36), nullable=True),
        sa.Column("seller_count", sa.Integer(), nullable=False),
        sa.Column("buy_box_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("buy_box_seller_id", sa.String(length=64), nullable=True),
        sa.Column("stock_available", sa.Boolean(), nullable=False),
        sa.Column("captured_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_market_gap_snapshots_captured_at"),
        "market_gap_snapshots",
        ["captured_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_market_gap_snapshots_catalog_product_id"),
        "market_gap_snapshots",
        ["catalog_product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_market_gap_snapshots_opportunity_id"),
        "market_gap_snapshots",
        ["opportunity_id"],
        unique=False,
    )
    op.create_table(
        "opportunity_lifecycle_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("opportunity_id", sa.String(length=36), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "FOUND",
                "VALIDATED",
                "PUBLISHED",
                "SOLD",
                "EXPIRED",
                "CANCELLED",
                name="lifecyclestage",
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_opportunity_lifecycle_events_occurred_at"),
        "opportunity_lifecycle_events",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_opportunity_lifecycle_events_opportunity_id"),
        "opportunity_lifecycle_events",
        ["opportunity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_opportunity_lifecycle_events_stage"),
        "opportunity_lifecycle_events",
        ["stage"],
        unique=False,
    )
    op.create_table(
        "market_gap_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("catalog_product_id", sa.String(length=64), nullable=False),
        sa.Column("opportunity_id", sa.String(length=36), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "LOWEST_SELLER_DISAPPEARED",
                "BUY_BOX_PRICE_INCREASED",
                "SELLER_COUNT_DROPPED",
                "STOCK_RECOVERED",
                name="marketgapeventtype",
            ),
            nullable=False,
        ),
        sa.Column("previous_snapshot_id", sa.String(length=36), nullable=True),
        sa.Column("current_snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["current_snapshot_id"],
            ["market_gap_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_snapshot_id"],
            ["market_gap_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_market_gap_events_catalog_product_id"),
        "market_gap_events",
        ["catalog_product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_market_gap_events_detected_at"), "market_gap_events", ["detected_at"], unique=False
    )
    op.create_index(
        op.f("ix_market_gap_events_event_type"), "market_gap_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_market_gap_events_opportunity_id"),
        "market_gap_events",
        ["opportunity_id"],
        unique=False,
    )
    # Adjusted by hand: 138 real Opportunity rows already exist in
    # production. A straight `nullable=False` ADD COLUMN would fail
    # against them (no value to satisfy the constraint) — add nullable,
    # backfill every existing row to the same LifecycleStage.FOUND the
    # ORM already defaults new rows to, then tighten to NOT NULL. Matches
    # the existing enum column convention here (Postgres stores the
    # member *name*, e.g. "APPROVED", not the lowercase value — confirmed
    # against the real `opportunities.status` column before writing this).
    op.add_column(
        "opportunities",
        sa.Column(
            "lifecycle_stage",
            sa.Enum(
                "FOUND",
                "VALIDATED",
                "PUBLISHED",
                "SOLD",
                "EXPIRED",
                "CANCELLED",
                name="lifecyclestage",
            ),
            nullable=True,
        ),
    )
    op.execute("UPDATE opportunities SET lifecycle_stage = 'FOUND' WHERE lifecycle_stage IS NULL")
    op.alter_column("opportunities", "lifecycle_stage", nullable=False)
    op.add_column("opportunities", sa.Column("confidence_score", sa.Integer(), nullable=True))
    op.add_column("opportunities", sa.Column("confidence_breakdown", sa.Text(), nullable=True))
    op.create_index(
        op.f("ix_opportunities_lifecycle_stage"), "opportunities", ["lifecycle_stage"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_opportunities_lifecycle_stage"), table_name="opportunities")
    op.drop_column("opportunities", "confidence_breakdown")
    op.drop_column("opportunities", "confidence_score")
    op.drop_column("opportunities", "lifecycle_stage")
    op.drop_index(op.f("ix_market_gap_events_opportunity_id"), table_name="market_gap_events")
    op.drop_index(op.f("ix_market_gap_events_event_type"), table_name="market_gap_events")
    op.drop_index(op.f("ix_market_gap_events_detected_at"), table_name="market_gap_events")
    op.drop_index(op.f("ix_market_gap_events_catalog_product_id"), table_name="market_gap_events")
    op.drop_table("market_gap_events")
    op.drop_index(
        op.f("ix_opportunity_lifecycle_events_stage"), table_name="opportunity_lifecycle_events"
    )
    op.drop_index(
        op.f("ix_opportunity_lifecycle_events_opportunity_id"),
        table_name="opportunity_lifecycle_events",
    )
    op.drop_index(
        op.f("ix_opportunity_lifecycle_events_occurred_at"),
        table_name="opportunity_lifecycle_events",
    )
    op.drop_table("opportunity_lifecycle_events")
    op.drop_index(op.f("ix_market_gap_snapshots_opportunity_id"), table_name="market_gap_snapshots")
    op.drop_index(
        op.f("ix_market_gap_snapshots_catalog_product_id"), table_name="market_gap_snapshots"
    )
    op.drop_index(op.f("ix_market_gap_snapshots_captured_at"), table_name="market_gap_snapshots")
    op.drop_table("market_gap_snapshots")
    op.drop_index(op.f("ix_listing_drafts_status"), table_name="listing_drafts")
    op.drop_index(op.f("ix_listing_drafts_opportunity_id"), table_name="listing_drafts")
    op.drop_table("listing_drafts")
    op.drop_index(op.f("ix_analytics_events_recorded_at"), table_name="analytics_events")
    op.drop_index(op.f("ix_analytics_events_opportunity_id"), table_name="analytics_events")
    op.drop_index(op.f("ix_analytics_events_event_type"), table_name="analytics_events")
    op.drop_table("analytics_events")
    # ### end Alembic commands ###
